### ISSUE TITLE
Child bridge crashes

### ISSUE THREAD

**Issue by hmangnx** [senorshaun/homebridge-nuheat#17]
Everyday I get an error that the child bridge crashes and it keeps trying to launch over and over again. Not sure why. 

![image](https://github.com/user-attachments/assets/c07c8f2d-bddc-4ac6-87da-6132ec4b77a7)

**Comment by hmangnx** [comment]
For more info, the plug-in works fine for a while when you reboot the server and/or restart the child bridge. But after a little bit of time, it will just keep crashing and reload over and over again until another restart. Not sure if it is because at some point it gets different data from the NuHeat api and is causing it to crash.

**Comment by senorshaun** [comment]
Have you put it in debug to see the json it’s getting backOn Nov 3, 2024, at 3:25 PM, HMAN ***@***.***> wrote:﻿
For more info, the plug-in works fine for a while when you reboot the server and/or restart the child bridge. But after a little bit of time, it will just keep crashing and reload over and over again until another restart. Not sure if it is because at some point it gets different data from the NuHeat api and is causing it to crash.

**Comment by hmangnx** [comment]
Ok I have figured out what triggers the crashes. It is when away mode is turned on. And now that I have turned on debug mode I see this:

![image](https://github.com/user-attachments/assets/41e07465-db16-4d53-9bd2-8336e89ae208)

Not sure if it is because it says Setting %s away mode to true is why it is crashing.

**Comment by senorshaun** [comment]
That just goes to show how I never use those switches. It's been broken for forever. 1.2.3 should fix it
