### ISSUE TITLE
New NuHeat API for 2019!

### ISSUE THREAD

**Issue by dsully** [senorshaun/homebridge-nuheat#2]
NuHeat just announced a real API, available starting 2019-01-15:

https://lp.nuheat.com/blog/floor-heating-for-the-connected-home

https://api.mynuheat.com

It'd be great if this project was updated to consume it.

Thanks!

**Comment by senorshaun** [comment]
Just looked through this. Would have been awesome if this was around when I was writing the plugin, but I'm not seeing what functionality it has that HomeKit could consume. What would you want to see implemented that the plugin doesn't already do?

**Comment by dinostop** [comment]
The 1 thing I would like to see changed, added, or adjusted would be currently the max temp is 100 degrees but I set mine higher than that.  Can this get changed so that the max temp is higher?

**Comment by senorshaun** [comment]
@dinostop its been a while since I worked on this so take this with a grain of salt. I think since the device type is a thermostat, the max setpoint imposed by HomeKit is 100. Check to see if you can find any HomeKit devices that can do above 100. Or if there is a different device type (maybe like a radiator or something) that it could be switched to. 
The client I wrote this for already had their desired set points, the highest of which was 96, so this wouldn’t have been something I looked that much in to
